[package]
name = "halo2-link-circuit"
version = "0.1.0"
edition = "2021"

[dependencies]
ff = "0.13.0"
halo2_proofs = { git = "https://github.com/txaty/halo2.git", branch ="plonk-multi-row" }
halo2curves = { version = "0.6.1", default-features = false }
